const private_key = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBgPM7cjv07BJTqr7pRxJrEUO0dN/kSS+FTdi9mj6zragAAAJh2llqTdpZa
kwAAAAtzc2gtZWQyNTUxOQAAACBgPM7cjv07BJTqr7pRxJrEUO0dN/kSS+FTdi9mj6zrag
AAAEA6IGOqI7NfTe/EtbME+ByQJsX9mRhomSdNYJit1CE3K2A8ztyO/TsElOqvulHEmsRQ
7R03+RJL4VN2L2aPrOtqAAAAE2RhbmlAV2luLWRhbm9uaW5vdW4BAg==
-----END OPENSSH PRIVATE KEY-----`;
